name: ffmpeg_kit_extended_flutter
description: FFmpeg Kit Extended for Flutter. Supports Android, iOS and macOS platforms.
repository: https://github.com/akashskypatel/ffmpeg-kit-extended
issue_tracker: https://github.com/akashskypatel/ffmpeg-kit-extended/issues
homepage: https://github.com/akashskypatel/ffmpeg-kit-extended
version: 6.0.3

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.akashskypatel.ffmpegkit.extended_flutter
        pluginClass: FFmpegKitFlutterPlugin
      ios:
        pluginClass: FFmpegKitFlutterPlugin
      macos:
        pluginClass: FFmpegKitFlutterPlugin
      linux:
        pluginClass: FFmpegKitFlutterPlugin
      windows:
        pluginClass: FFmpegKitFlutterPlugin

dependencies:
  ffmpeg_kit_extended_flutter_platform_interface:
    path: ../flutter_platform_interface
  flutter:
    sdk: flutter
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.5
