name: ffmpeg_kit_extended_flutter_platform_interface
description: A common platform interface for ffmpeg_kit_extended plugin.
repository: https://github.com/akashskypatel/ffmpeg-kit-extended
issue_tracker: https://github.com/akashskypatel/ffmpeg-kit-extended/issues
homepage: https://github.com/akashskypatel/ffmpeg-kit-extended
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 0.2.1

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
